# Generated by Django 4.2.18 on 2025-01-23 08:28

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StaticData', '0001_initial'),
        ('ProjectContract', '0011_contract_sub_project_alter_contractpayments_name'),
        ('ProjectTDL', '0003_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=200, null=True, verbose_name='uid')),
                ('email_type', models.CharField(choices=[('IN', 'Входящие'), ('OUT', 'Исходящие')], default=('IN', 'Входящие'), max_length=10, verbose_name='Тип Сообщения')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка')),
                ('subject', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тема письма')),
                ('body', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Тело письма')),
                ('sender', models.CharField(blank=True, max_length=300, null=True, verbose_name='Отправитель')),
                ('receiver', models.CharField(blank=True, max_length=300, null=True, verbose_name='Получатель')),
                ('email_stamp', models.DateTimeField(blank=True, null=True, verbose_name='дата письма')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('building_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.buildingtype', verbose_name='Здание')),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StaticData.category', verbose_name='Категория')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contractor', verbose_name='Подрядчик')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectTDL.task', verbose_name='Род. Задача')),
                ('project_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.projectsite', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mail',
                'ordering': ['-email_stamp'],
            },
        ),
    ]
