# Generated by Django 5.0.6 on 2026-03-13 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectContract', '0001_initial'),
        ('ProjectTDL', '0001_initial'),
        ('StaticData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=200, null=True, verbose_name='uid')),
                ('email_type', models.CharField(choices=[('IN', 'Входящие'), ('OUT', 'Исходящие')], default=('IN', 'Входящие'), max_length=10, verbose_name='Тип Сообщения')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('info', models.CharField(blank=True, choices=[('APPROVED', 'Согласовано'), ('TASK', 'Задача'), ('FINANCIAL', 'Финансы')], default='TASK', max_length=20, null=True, verbose_name='Тип информации')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка')),
                ('subject', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тема письма')),
                ('sender', models.CharField(blank=True, max_length=300, null=True, verbose_name='Отправитель')),
                ('receiver', models.CharField(blank=True, max_length=300, null=True, verbose_name='Получатель')),
                ('email_stamp', models.DateTimeField(blank=True, null=True, verbose_name='дата письма')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важное')),
                ('folder', models.CharField(choices=[('inbox', 'Входящие'), ('sent', 'Отправленные'), ('drafts', 'Черновики'), ('archive', 'Архив'), ('trash', 'Корзина')], default='inbox', max_length=20, verbose_name='Папка')),
                ('building_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.buildingtype', verbose_name='Здание')),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StaticData.category', verbose_name='Категория')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contractor', verbose_name='Подрядчик')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectTDL.task', verbose_name='Род. Задача')),
                ('project_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.projectsite', verbose_name='Проект')),
                ('tasks', models.ManyToManyField(blank=True, related_name='emails', to='ProjectTDL.task', verbose_name='Задачи')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mail',
                'ordering': ['-email_stamp'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('size', models.IntegerField(verbose_name='Размер (байт)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Тип содержимого')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Emails.email', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
