# Generated by Django 5.2.16 on 2026-07-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='Content-ID'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_inline',
            field=models.BooleanField(default=False, verbose_name='Inline'),
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=models.TextField(blank=True, null=True, verbose_name='Скрытая копия'),
        ),
        migrations.AddField(
            model_name='email',
            name='cc',
            field=models.TextField(blank=True, null=True, verbose_name='Копия'),
        ),
    ]
