# Generated by Django 4.2.18 on 2025-02-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='info',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Согласовано'), ('TASK', 'Задача'), ('FINANCIAL', 'Финансы')], default='TASK', max_length=20, null=True, verbose_name='Тип информации'),
        ),
    ]
