# Generated by Django 4.2.18 on 2026-03-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0002_email_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='body',
        ),
    ]
