# Generated by Django 5.2.16 on 2026-07-22 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0002_attachment_content_id_attachment_is_inline_email_bcc_and_more'),
        ('email_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_messages', to='email_ui.contact', verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='email',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка отправки'),
        ),
        migrations.AddField(
            model_name='email',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='In-Reply-To'),
        ),
        migrations.AddField(
            model_name='email',
            name='message_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Message-ID'),
        ),
        migrations.AddField(
            model_name='email',
            name='references',
            field=models.TextField(blank=True, null=True, verbose_name='References'),
        ),
        migrations.AddField(
            model_name='email',
            name='reply_to',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ответить кому'),
        ),
        migrations.AddField(
            model_name='email',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='email',
            name='sent_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('bounced', 'Возвращено')], default='draft', max_length=20, verbose_name='Статус отправки'),
        ),
        migrations.AddField(
            model_name='email',
            name='smtp_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_ui.smtpaccount', verbose_name='SMTP аккаунт'),
        ),
        migrations.AddField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_ui.emailtemplate', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='email',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Thread ID'),
        ),
    ]
