# Generated by Django 4.2.18 on 2026-03-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0005_taskduedatehistory'),
        ('Emails', '0003_remove_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Входящие'), ('sent', 'Отправленные'), ('drafts', 'Черновики'), ('archive', 'Архив'), ('trash', 'Корзина')], default='inbox', max_length=20, verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='email',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='emails/html/', verbose_name='Файл с телом письма'),
        ),
        migrations.AddField(
            model_name='email',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Важное'),
        ),
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='email',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='emails', to='ProjectTDL.task', verbose_name='Задачи'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='emails/attachments/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('size', models.IntegerField(verbose_name='Размер (байт)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Тип содержимого')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Emails.email', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
