# Generated by Django 4.2.18 on 2026-07-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0003_email_contact_email_error_message_email_in_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('email', 'filename')},
        ),
    ]
