# Generated by Django 5.2.16 on 2026-07-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0004_attachment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together=set(),
        ),
    ]
