# Generated by Django 4.2.18 on 2026-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0004_email_folder_email_html_file_email_is_important_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='email',
            name='html_file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_path',
            field=models.CharField(default=1, max_length=500, verbose_name='Путь к файлу'),
            preserve_default=False,
        ),
    ]
