# Generated by Django 6.0.7 on 2026-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0006_email_sender_name'),
        ('ProjectTDL', '0003_remove_tasknode_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='emails', to='ProjectTDL.tasknode', verbose_name='Задачи'),
        ),
    ]
