# Generated by Django 6.0.7 on 2026-07-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0007_alter_email_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='parent',
        ),
    ]
