# Generated by Django 4.2.18 on 2026-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0008_remove_email_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='body_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст тела'),
        ),
    ]
