# Generated by Django 5.2.16 on 2026-10-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0009_email_body_text'),
        ('ProjectContract', '0013_tag_attachment_contract_tags_taggeditem'),
        ('ProjectTDL', '0020_usersettings_table_sort'),
        ('StaticData', '0003_remove_projectsite_default_sub_project_and_more'),
        ('email_ui', '0008_emailviewsettings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['folder', 'email_stamp'], name='Emails_emai_folder_6147b8_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['folder', 'is_read'], name='Emails_emai_folder_479612_idx'),
        ),
    ]
