# Generated by Django 5.0.4 on 2024-08-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StaticData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена договора')),
                ('proposal_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proposal')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='план.начало')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='план.завершение')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='длительность')),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaticData.projectsite', verbose_name='Проект')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contractor', verbose_name='Подрядчик')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
        migrations.CreateModel(
            name='ContractPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Наименование платежа')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена')),
                ('percent', models.FloatField(blank=True, null=True, verbose_name='процент')),
                ('made_payment', models.BooleanField(default=False, verbose_name='Оплачено?')),
                ('custom_formula', models.CharField(blank=True, max_length=255)),
                ('use_custom_formula', models.BooleanField(default=False)),
                ('field_to_overwrite', models.CharField(blank=True, choices=[('price', 'цена')], max_length=255)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='план.начало')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='длительность')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='план.завершение')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contract', verbose_name='Договор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ProjectContract.contractpayments')),
            ],
            options={
                'verbose_name': 'договор Оплата',
                'verbose_name_plural': 'договоры Оплаты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConcretePaymentCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contract', verbose_name='Договор')),
                ('contract_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contractpayments')),
            ],
            options={
                'verbose_name': 'Payment Calendar',
                'verbose_name_plural': 'Payment Calendars',
            },
        ),
    ]
