# Generated by Django 4.2.18 on 2026-07-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sub_project',
        ),
    ]
