# Generated by Django 5.0.4 on 2024-09-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='propolsal_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Proposal link'),
        ),
        migrations.AlterField(
            model_name='contractpayments',
            name='custom_formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
