# Generated by Django 5.0.4 on 2024-09-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0002_contract_propolsal_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='propolsal_link',
            new_name='proposal_link',
        ),
        migrations.AlterField(
            model_name='contractpayments',
            name='use_custom_formula',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
