# Generated by Django 5.0.4 on 2024-09-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0003_rename_propolsal_link_contract_proposal_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayments',
            name='field_to_overwrite',
            field=models.CharField(blank=True, choices=[('price', 'цена')], max_length=255, null=True),
        ),
    ]
