# Generated by Django 5.2.16 on 2026-09-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0004_status_client_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('bucket', models.CharField(choices=[('fact', 'Факт'), ('guaranteed', 'Гарантировано'), ('likely', 'Вероятно'), ('planned', 'Запланировано')], max_length=20, verbose_name='Корзина')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_entries', to='ProjectContract.contract', verbose_name='Договор')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_entries', to='ProjectContract.contractpayments', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Строка ДДС',
                'verbose_name_plural': 'ДДС (материализованное)',
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['contract', 'date'], name='ProjectCont_contrac_9a336c_idx'), models.Index(fields=['bucket', 'date'], name='ProjectCont_bucket_c0f75d_idx')],
            },
        ),
    ]
