# Generated by Django 5.0.4 on 2024-09-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0004_alter_contractpayments_field_to_overwrite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='proposal_link',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Proposal link'),
        ),
    ]
