# Generated by Django 5.2.16 on 2026-09-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0005_cashflowentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayments',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='план.завершение'),
        ),
        migrations.AlterField(
            model_name='contractpayments',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='длительность'),
        ),
        migrations.AlterField(
            model_name='contractpayments',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='план.начало'),
        ),
    ]
