# Generated by Django 5.0.4 on 2024-11-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0005_alter_contract_proposal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpayments',
            name='payment_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание платежа'),
        ),
        migrations.AlterField(
            model_name='contractpayments',
            name='duration',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='длительность'),
        ),
    ]
