# Generated by Django 5.2.16 on 2026-09-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0006_alter_contractpayments_due_date_and_more'),
        ('ProjectTDL', '0018_usersettings_panel_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('amount_applied', models.DecimalField(decimal_places=2, help_text='Сумма платежа, привязанная к этой задаче', max_digits=12, verbose_name='Применённая сумма')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='ProjectContract.contractpayments', verbose_name='Платёж')),
                ('task_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='ProjectTDL.tasknode', verbose_name='Задача (TaskNode)')),
            ],
            options={
                'verbose_name': 'Привязка платёж ↔ задача',
                'verbose_name_plural': 'Привязки платёж ↔ задача',
                'ordering': ['id'],
                'unique_together': {('payment', 'task_node')},
            },
        ),
    ]
