# Generated by Django 5.0.4 on 2024-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0007_alter_contractor_name_alter_contractpayments_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpayments',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('advance', 'Аванс'), ('payment', 'Платеж')], default='advance', max_length=200, null=True, verbose_name='Тип платежа'),
        ),
    ]
