# Generated by Django 5.2.16 on 2026-09-14 10:38

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Sum


def create_primary_estimates(apps, schema_editor):
    """Data migration (DMC-3): свёртка платежей в первичную смету.

    Для каждого договора создаёт смету «Первичная смета» со статусом
    approved, total_amount = sum(ContractPayments.price), и связывает её
    через Contract.estimate.
    """
    Contract = apps.get_model('ProjectContract', 'Contract')
    ContractEstimate = apps.get_model('ProjectContract', 'ContractEstimate')
    ContractPayments = apps.get_model('ProjectContract', 'ContractPayments')
    db_alias = schema_editor.connection.alias
    for contract in Contract.objects.using(db_alias).all():
        total = ContractPayments.objects.using(db_alias).filter(
            contract=contract).aggregate(total=Sum('price'))['total'] or 0
        estimate = ContractEstimate.objects.using(db_alias).create(
            contract=contract,
            name='Первичная смета',
            status='approved',
            total_amount=total,
        )
        contract.estimate = estimate
        contract.save(update_fields=['estimate'])


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0007_paymenttasklink'),
        ('ProjectTDL', '0018_usersettings_panel_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждена')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая сумма')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='ProjectContract.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_main', to='ProjectContract.contractestimate', verbose_name='Основная смета'),
        ),
        migrations.CreateModel(
            name='EstimateConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('unit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Объём')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за ед.')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='ProjectContract.contractestimate', verbose_name='Смета')),
                ('task_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_concepts', to='ProjectTDL.tasknode', verbose_name='Задача (TaskNode)')),
            ],
            options={
                'verbose_name': 'Позиция сметы',
                'verbose_name_plural': 'Позиции сметы',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(create_primary_estimates, reverse_code=migrations.RunPython.noop),
    ]
