# Generated by Django 5.0.4 on 2025-01-16 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0008_contractpayments_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concretepaymentcalendar',
            options={'verbose_name': 'ДДС', 'verbose_name_plural': 'ДДС'},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='contractpayments',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='план.завершение'),
        ),
        migrations.AlterField(
            model_name='contractpayments',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('advance', 'Аванс'), ('intermediate', 'промежуточный '), ('final', 'финальный')], default='advance', max_length=200, null=True, verbose_name='Тип платежа'),
        ),
        migrations.AlterField(
            model_name='contractpayments',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='план.начало'),
        ),
    ]
