# Generated by Django 5.0.6 on 2024-08-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0008_remove_contractpayments_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpayments',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='процент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена'),
        ),
    ]
