# Generated by Django 5.2.16 on 2026-09-14 12:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


STATUS_TO_STAGE = {
    'draft': 'negotiation',
    'active': 'execution',
    'suspended': 'execution',
    'closed': 'closed',
    'canceled': 'closed',
}


def backfill_stages(apps, schema_editor):
    """DMC-5: начальный этап по статусу + одна запись журнала на договор."""
    Contract = apps.get_model('ProjectContract', 'Contract')
    ContractStageLog = apps.get_model('ProjectContract', 'ContractStageLog')
    today = datetime.date.today()
    for status, stage in STATUS_TO_STAGE.items():
        qs = Contract.objects.filter(status=status)
        qs.update(stage=stage)
        ContractStageLog.objects.bulk_create([
            ContractStageLog(contract_id=cid, stage=stage, date=today,
                             notes='Начальный этап (миграция 0009)')
            for cid in qs.values_list('id', flat=True)
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0008_contractestimate_contract_estimate_estimateconcept'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='next_step',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Следующий шаг'),
        ),
        migrations.AddField(
            model_name='contract',
            name='next_step_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего шага'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stage',
            field=models.CharField(choices=[('negotiation', 'Переговоры'), ('signing', 'Подписание'), ('advance', 'Аванс'), ('execution', 'Выполнение работ'), ('acceptance', 'Приёмка'), ('final_payment', 'Окончательный расчёт'), ('warranty', 'Гарантия'), ('closed', 'Закрыт')], default='negotiation', max_length=20, verbose_name='Этап'),
        ),
        migrations.CreateModel(
            name='ContractStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('stage', models.CharField(choices=[('negotiation', 'Переговоры'), ('signing', 'Подписание'), ('advance', 'Аванс'), ('execution', 'Выполнение работ'), ('acceptance', 'Приёмка'), ('final_payment', 'Окончательный расчёт'), ('warranty', 'Гарантия'), ('closed', 'Закрыт')], max_length=20, verbose_name='Этап')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('is_next_step', models.BooleanField(default=False, verbose_name='Запланированный шаг')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='ProjectContract.contract', verbose_name='Договор')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Этап договора',
                'verbose_name_plural': 'Этапы договоров (журнал)',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.RunPython(backfill_stages, migrations.RunPython.noop),
    ]
