# Generated by Django 5.0.6 on 2024-08-01 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0009_contractpayments_percent_alter_contract_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractpayments',
            name='parent',
        ),
        migrations.AddField(
            model_name='contractpayments',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='ProjectContract.contractpayments'),
        ),
    ]
