# Generated by Django 5.2.16 on 2026-09-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0009_contract_next_step_contract_next_step_date_and_more'),
        ('ProjectTDL', '0018_usersettings_panel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractchangelog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ProjectTDL.tasknode', verbose_name='Задача'),
        ),
    ]
