# Generated by Django 4.2.18 on 2025-01-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaticData', '0001_initial'),
        ('ProjectContract', '0010_contract_due_date_contract_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='sub_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='StaticData.subproject', verbose_name='Подпроект'),
        ),
        migrations.AlterField(
            model_name='contractpayments',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименование платежа'),
        ),
    ]
