# Generated by Django 5.2.16 on 2026-09-14 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0010_contractchangelog_task'),
        ('ProjectTDL', '0018_usersettings_panel_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('due_date', models.DateField(verbose_name='Напомнить не позже')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='Текст')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Уведомлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда уведомлено')),
                ('is_done', models.BooleanField(default=False, verbose_name='Закрыто')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='ProjectContract.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='ProjectContract.contractpayments', verbose_name='Платёж')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='ProjectTDL.tasknode', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['due_date', '-id'],
            },
        ),
    ]
