# Generated by Django 5.0.6 on 2024-08-01 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0010_remove_contractpayments_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractpayments',
            options={'ordering': ['id'], 'verbose_name': 'договор Оплата', 'verbose_name_plural': 'договоры Оплаты'},
        ),
        migrations.RemoveField(
            model_name='contractpayments',
            name='predecessor',
        ),
        migrations.AddField(
            model_name='contractpayments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ProjectContract.contractpayments'),
        ),
    ]
