# Generated by Django 5.0.6 on 2024-08-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0011_alter_contractpayments_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Календарь платежей',
                'verbose_name_plural': 'Календари платежей',
                'ordering': ['date'],
            },
        ),
    ]
