# Generated by Django 5.2.16 on 2026-09-14 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0011_contractreminder'),
        ('ProjectTDL', '0018_usersettings_panel_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('body', models.TextField(verbose_name='Текст комментария')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='ProjectTDL.tasknode', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарий к задаче',
                'verbose_name_plural': 'Комментарии к задачам',
                'ordering': ['-creation_stamp', '-id'],
            },
        ),
    ]
