# Generated by Django 5.0.6 on 2024-08-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0012_paymentcalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcalendar',
            name='contract_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contractpayments'),
        ),
    ]
