# Generated by Django 5.0.6 on 2024-08-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0013_paymentcalendar_contract_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentCalendar',
            new_name='ConcretePaymentCalendar',
        ),
        migrations.AlterModelOptions(
            name='concretepaymentcalendar',
            options={'verbose_name': 'Payment Calendar', 'verbose_name_plural': 'Payment Calendars'},
        ),
    ]
