# Generated by Django 5.2.16 on 2026-10-08 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0013_tag_attachment_contract_tags_taggeditem'),
        ('StaticData', '0003_remove_projectsite_default_sub_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateconcept',
            name='building_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_concepts', to='StaticData.buildingnumber', verbose_name='Здание'),
        ),
        migrations.AddField(
            model_name='estimateconcept',
            name='design_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_concepts', to='StaticData.designchapter', verbose_name='Раздел'),
        ),
    ]
