# Generated by Django 5.0.3 on 2024-03-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectContract', '0001_initial'),
        ('StaticData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наим. Задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='цена')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='дата завершения')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('building_number', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.buildingnumber', verbose_name='Здание')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectContract.contract', verbose_name='Договор')),
                ('contractor', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contractor', verbose_name='Ответсвенный')),
                ('design_chapter', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.designchapter', verbose_name='Раздел')),
                ('project_site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StaticData.projectsite', verbose_name='Проект')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='StaticData.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заметки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='цена')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='дата завершения')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectTDL.task', verbose_name='Наим. Задачи')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
