# Generated by Django 4.2.18 on 2025-01-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaticData', '0001_initial'),
        ('ProjectTDL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='project_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.projectsite', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectTDL.task', verbose_name='Род. Задача'),
        ),
    ]
