# Generated by Django 6.0.7 on 2026-07-28 06:55

import django.db.models.deletion
import mptt.fields
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0006_email_sender_name'),
        ('ProjectContract', '0001_initial'),
        ('ProjectTDL', '0001_initial'),
        ('StaticData', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('task', 'Задача'), ('subtask', 'Подзадача')], default='task', max_length=10, verbose_name='Тип')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Цена')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Завершение')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('building_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.buildingnumber', verbose_name='Здание')),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StaticData.category', verbose_name='Категория')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectContract.contract', verbose_name='Договор')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectContract.contractor', verbose_name='Ответственный')),
                ('design_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StaticData.designchapter', verbose_name='Раздел')),
                ('emails', models.ManyToManyField(blank=True, related_name='task_nodes', to='Emails.email', verbose_name='Письма')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_nodes', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ProjectTDL.tasknode', verbose_name='Родитель')),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaticData.projectsite', verbose_name='Проект')),
                ('status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='StaticData.status', verbose_name='Статус')),
                ('sub_project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StaticData.subproject', verbose_name='Подпроект')),
            ],
            options={
                'verbose_name': 'Задача (дерево)',
                'verbose_name_plural': 'Задачи (дерево)',
            },
        ),
    ]
