# Generated by Django 6.0.7 on 2026-07-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0002_tasknode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknode',
            name='emails',
        ),
    ]
