# Generated by Django 4.2.18 on 2025-01-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0002_alter_email_project_site_alter_subtask_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
