# Generated by Django 4.2.18 on 2025-02-11 11:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0003_delete_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
