# Generated by Django 6.0.7 on 2026-07-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0004_migrate_task_to_tasknode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectTDL.tasknode', verbose_name='Род. Задача'),
        ),
        migrations.AlterField(
            model_name='taskduedatehistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_date_history', to='ProjectTDL.tasknode', verbose_name='Задача'),
        ),
    ]
