# Generated by Django 4.2.18 on 2025-10-14 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectTDL', '0004_alter_subtask_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDueDateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_due_date', models.DateField(blank=True, null=True, verbose_name='Предыдущая дата')),
                ('new_due_date', models.DateField(blank=True, null=True, verbose_name='Новая дата')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_date_history', to='ProjectTDL.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'История изменения срока задачи',
                'verbose_name_plural': 'История изменений сроков задач',
                'ordering': ['-change_date'],
            },
        ),
    ]
