# Generated by Django 6.0.7 on 2026-07-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0006_alter_subtask_parent_alter_taskduedatehistory_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskduedatehistory',
            name='task_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_date_history', to='ProjectTDL.tasknode', verbose_name='Задача (дерево)'),
        ),
    ]
