# Generated by Django 6.0.7 on 2026-07-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0007_taskduedatehistory_task_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='task',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='design_chapter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project_site',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sub_project',
        ),
        migrations.RemoveField(
            model_name='taskduedatehistory',
            name='task',
        ),
        migrations.AlterField(
            model_name='taskduedatehistory',
            name='task_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_date_history', to='ProjectTDL.tasknode', verbose_name='Задача'),
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
