# Generated by Django 6.0.7 on 2026-07-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0008_remove_email_parent'),
        ('ProjectTDL', '0008_remove_task_building_number_remove_task_category_and_more'),
        ('email_ui', '0005_alter_emailtasklink_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
