# Generated by Django 4.2.18 on 2026-07-31 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaticData', '0002_projectsite_default_category_and_more'),
        ('ProjectTDL', '0010_projectpin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpin',
            options={'verbose_name': 'Закреплённый проект', 'verbose_name_plural': 'Закреплённые проекты'},
        ),
        migrations.RemoveField(
            model_name='tasknode',
            name='sub_project',
        ),
        migrations.AlterField(
            model_name='projectpin',
            name='project_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaticData.projectsite', verbose_name='Проект'),
        ),
    ]
