# Generated by Django 4.2.18 on 2026-08-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0013_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='default_building',
            field=models.BooleanField(default=False, verbose_name='Заполнять здание из контекста'),
        ),
    ]
