# Generated by Django 5.2.16 on 2026-08-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0014_usersettings_default_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='column_widths',
            field=models.JSONField(default=dict, verbose_name='Ширины колонок'),
        ),
    ]
