# Generated by Django 5.2.16 on 2026-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0015_usersettings_column_widths'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='page_length',
            field=models.IntegerField(blank=True, null=True, verbose_name='Записей на страницу'),
        ),
    ]
