# Generated by Django 5.2.16 on 2026-08-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0016_usersettings_page_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='column_order',
            field=models.JSONField(default=list, verbose_name='Порядок колонок'),
        ),
    ]
