# Generated by Django 5.2.16 on 2026-08-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0017_usersettings_column_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='panel_fields',
            field=models.JSONField(default=dict, verbose_name='Поля панели свойств'),
        ),
    ]
