# Generated by Django 5.2.16 on 2026-09-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0013_tag_attachment_contract_tags_taggeditem'),
        ('ProjectTDL', '0018_usersettings_panel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknode',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='ProjectContract.tag', verbose_name='Теги'),
        ),
    ]
