# Generated by Django 4.2.18 on 2026-09-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0019_tasknode_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='table_sort',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Сортировка строк таблицы (?sort=)'),
        ),
    ]
