# Generated by Django 4.2.18 on 2026-07-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название канала')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Username (@)')),
                ('channel_id', models.BigIntegerField(blank=True, null=True, verbose_name='Channel ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_parsed', models.DateTimeField(blank=True, null=True, verbose_name='Последний парсинг')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
            ],
            options={
                'verbose_name': 'Канал Telegram',
                'verbose_name_plural': 'Каналы Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID сообщения')),
                ('channel_name', models.CharField(blank=True, max_length=200, verbose_name='Имя канала')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('html_text', models.TextField(blank=True, verbose_name='Текст (HTML)')),
                ('date', models.DateTimeField(verbose_name='Дата сообщения')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('links', models.JSONField(blank=True, default=list, verbose_name='Ссылки')),
                ('reactions', models.JSONField(blank=True, default=dict, verbose_name='Реакции')),
                ('total_reactions', models.PositiveIntegerField(default=0, verbose_name='Всего реакций')),
                ('importance', models.IntegerField(choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая'), (4, 'Критическая')], default=2, verbose_name='Важность')),
                ('has_media', models.BooleanField(default=False, verbose_name='Есть медиа')),
                ('media_type', models.CharField(blank=True, max_length=50, verbose_name='Тип медиа')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
                ('source', models.CharField(choices=[('api', 'API'), ('html', 'HTML-экспорт')], default='api', max_length=20, verbose_name='Источник')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TelegramParser.telegramchannel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Сообщение Telegram',
                'verbose_name_plural': 'Сообщения Telegram',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ParseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('api', 'API'), ('html', 'HTML-импорт')], default='api', max_length=20, verbose_name='Операция')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('messages_found', models.PositiveIntegerField(default=0, verbose_name='Найдено')),
                ('messages_saved', models.PositiveIntegerField(default=0, verbose_name='Сохранено')),
                ('messages_skipped', models.PositiveIntegerField(default=0, verbose_name='Пропущено (дубли)')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('done', 'Завершено'), ('error', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TelegramParser.telegramchannel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Лог парсинга',
                'verbose_name_plural': 'Логи парсинга',
                'ordering': ['-started_at'],
            },
        ),
    ]
