# Generated by Django 6.0.7 on 2026-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramParser', '0003_telegrammessage_content_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='html_text',
            field=models.TextField(blank=True, verbose_name='Текст (HTML)'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
