# Generated by Django 5.2.16 on 2026-07-22 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Emails', '0002_attachment_content_id_attachment_is_inline_email_bcc_and_more'),
        ('ProjectContract', '0001_initial'),
        ('ProjectTDL', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Тег письма',
                'verbose_name_plural': 'Теги писем',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMTPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('host', models.CharField(max_length=200, verbose_name='Хост')),
                ('port', models.IntegerField(default=587, verbose_name='Порт')),
                ('username', models.EmailField(max_length=254, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('use_tls', models.BooleanField(default=True, verbose_name='TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Email отправителя')),
                ('from_name', models.CharField(blank=True, max_length=100, verbose_name='Имя отправителя')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMTP аккаунт',
                'verbose_name_plural': 'SMTP аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectContract.contractor', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('conditions', models.JSONField(default=dict, help_text='Формат: {"field": "subject|sender|receiver|has_attachments", "operator": "contains|equals|regex", "value": "..."}', verbose_name='Условия')),
                ('actions', models.JSONField(default=dict, help_text='Формат: {"action": "add_tag", "params": {"tag_id": 1}}', verbose_name='Действия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Правило автоматизации',
                'verbose_name_plural': 'Правила автоматизации',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='EmailAutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время выполнения')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно')),
                ('action_taken', models.CharField(blank=True, max_length=200, verbose_name='Выполненное действие')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Emails.email', verbose_name='Письмо')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_ui.emailrule', verbose_name='Правило')),
            ],
            options={
                'verbose_name': 'Лог автоматизации',
                'verbose_name_plural': 'Логи автоматизации',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('subject_template', models.CharField(max_length=300, verbose_name='Шаблон темы')),
                ('body_template', models.TextField(verbose_name='Шаблон тела письма')),
                ('is_html', models.BooleanField(default=True, verbose_name='HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Переменная')),
                ('label', models.CharField(max_length=100, verbose_name='Описание')),
                ('default_value', models.CharField(blank=True, max_length=200, verbose_name='По умолчанию')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='email_ui.emailtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Переменная шаблона',
                'verbose_name_plural': 'Переменные шаблонов',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('label', models.CharField(choices=[('work', 'Рабочий'), ('personal', 'Личный'), ('other', 'Другое')], default='work', max_length=20, verbose_name='Тип')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_ui.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Email контакта',
                'verbose_name_plural': 'Email контактов',
                'unique_together': {('contact', 'email')},
            },
        ),
        migrations.CreateModel(
            name='EmailEmailTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tags', to='Emails.email', verbose_name='Письмо')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tags', to='email_ui.emailtag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег письма (связь)',
                'verbose_name_plural': 'Теги писем (связи)',
                'unique_together': {('email', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='EmailTaskLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('related', 'Связано'), ('created_from', 'Создано из письма'), ('created_task', 'Создана задача'), ('reference', 'Ссылка')], default='related', max_length=20, verbose_name='Тип связи')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто связал')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='Emails.email', verbose_name='Письмо')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_links', to='ProjectTDL.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Связь письма с задачей',
                'verbose_name_plural': 'Связи писем с задачами',
                'unique_together': {('email', 'task')},
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('filters', models.JSONField(verbose_name='Параметры фильтра')),
                ('folder', models.CharField(default='inbox', max_length=20, verbose_name='Папка')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Общий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохранённый фильтр',
                'verbose_name_plural': 'Сохранённые фильтры',
                'unique_together': {('name', 'user')},
            },
        ),
    ]
