# Generated by Django 6.0.7 on 2026-07-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectTDL', '0005_alter_subtask_parent_alter_taskduedatehistory_task'),
        ('email_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtasklink',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_links', to='ProjectTDL.tasknode', verbose_name='Задача'),
        ),
    ]
