# Generated by Django 6.0.7 on 2026-07-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emails', '0008_remove_email_parent'),
        ('ProjectTDL', '0008_remove_task_building_number_remove_task_category_and_more'),
        ('email_ui', '0004_emailtasklink_task_node'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailtasklink',
            unique_together={('email', 'task_node')},
        ),
        migrations.AlterField(
            model_name='emailtasklink',
            name='task_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_links', to='ProjectTDL.tasknode', verbose_name='Задача'),
        ),
        migrations.RemoveField(
            model_name='emailtasklink',
            name='task',
        ),
    ]
