# Generated by Django 5.2.16 on 2026-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_ui', '0005_alter_emailtasklink_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Отображаемое имя как в заголовках писем, lower', max_length=200, unique=True, verbose_name='Алиас (имя)')),
                ('email', models.EmailField(max_length=254, verbose_name='Твёрдая почта')),
                ('source', models.CharField(choices=[('sender_map', 'Карта отправителей'), ('contact', 'Контакт'), ('manual', 'Вручную')], default='manual', max_length=20, verbose_name='Источник')),
                ('verified', models.BooleanField(default=False, help_text='Применять в миграциях только проверенные', verbose_name='Проверен')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Алиас почты',
                'verbose_name_plural': 'Алиасы почты',
                'ordering': ['alias'],
            },
        ),
    ]
