# Generated by Django 5.2.16 on 2026-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_ui', '0006_emailalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('contacts', models.ManyToManyField(blank=True, related_name='contact_groups', to='email_ui.contact', verbose_name='Контакты')),
                ('subgroups', models.ManyToManyField(blank=True, related_name='parent_groups', to='email_ui.contactgroup', verbose_name='Вложенные группы')),
            ],
            options={
                'verbose_name': 'Группа адресатов',
                'verbose_name_plural': 'Группы адресатов',
                'ordering': ['name'],
            },
        ),
    ]
