# Generated by Django 5.2.16 on 2026-09-17 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_ui', '0007_contactgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailViewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_body_preview', models.BooleanField(default=True, verbose_name='Показывать начало текста под темой письма')),
                ('preview_length', models.PositiveIntegerField(default=120, verbose_name='Символов в превью')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_view_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки почты',
                'verbose_name_plural': 'Настройки почты',
            },
        ),
    ]
