# Generated by Django 5.2.16 on 2026-09-10 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Emails', '0008_remove_email_parent'),
        ('ProjectContract', '0006_alter_contractpayments_due_date_and_more'),
        ('ProjectTDL', '0018_usersettings_panel_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='accdb: код', unique=True, verbose_name='Код')),
                ('section', models.CharField(blank=True, default='', help_text='accdb: раздел (код из [Разделы])', max_length=20, verbose_name='Раздел')),
                ('building_no', models.CharField(blank=True, default='', help_text='accdb: Номер здания', max_length=20, verbose_name='Номер здания')),
                ('cipher', models.CharField(blank=True, db_index=True, default='', help_text='accdb: шифр', max_length=200, verbose_name='Шифр')),
                ('file_name', models.CharField(blank=True, default='', help_text='accdb: Назв Эл файла', max_length=300, verbose_name='Имя эл. файла')),
                ('approval_status', models.CharField(blank=True, default='', help_text='accdb: согласование', max_length=50, verbose_name='Согласование')),
                ('approval_date', models.DateField(blank=True, help_text='accdb: дата согласования', null=True, verbose_name='Дата согласования')),
                ('submitted_flag', models.CharField(blank=True, default='', help_text='accdb: подано на согласование', max_length=10, verbose_name='Подано')),
                ('change_descr', models.TextField(blank=True, default='', help_text='accdb: Описание изм', verbose_name='Описание изменений')),
                ('building_name', models.CharField(blank=True, default='', help_text='accdb: Наименование здания', max_length=300, verbose_name='Здание')),
                ('submit_date', models.DateField(blank=True, help_text='accdb: Дата подачи на согласование', null=True, verbose_name='Дата подачи')),
                ('acts', models.CharField(blank=True, default='', help_text='accdb: Акты', max_length=200, verbose_name='Акты')),
                ('contractor_new', models.CharField(blank=True, default='', help_text='accdb: разраб_нов', max_length=20, verbose_name='Разраб. нов.')),
                ('accdb_row_hash', models.CharField(blank=True, default='', help_text='sha1 конкатенации полей — для ночного check_accdb_drift (DOC-5)', max_length=64, verbose_name='Хеш строки accdb')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_entries', to='ProjectContract.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Запись реестра РД',
                'verbose_name_plural': 'Реестр РД',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_no', models.CharField(max_length=50, verbose_name='№ накладной')),
                ('waybill_date', models.DateField(blank=True, null=True, verbose_name='Дата накладной')),
                ('waybill_pdf', models.FileField(blank=True, null=True, upload_to='DocRegistry/issues/%Y/%m/', verbose_name='Накладная (PDF)')),
                ('network_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Папка выдачи (сеть)')),
                ('archived_old_rev', models.BooleanField(default=False, verbose_name='Старая ревизия убрана в архив')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдано')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='DocRegistry.docregisterentry', verbose_name='Запись реестра')),
            ],
            options={
                'verbose_name': 'Выдача в ПР',
                'verbose_name_plural': 'Выдачи в ПР',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='DocRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_no', models.PositiveIntegerField(default=1, verbose_name='№ ревизии')),
                ('file', models.FileField(blank=True, null=True, upload_to='DocRegistry/incoming/%Y/%m/', verbose_name='Файл ревизии')),
                ('sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получена')),
                ('source', models.CharField(choices=[('email', 'Из письма'), ('yadi', 'Yandex.Disk ссылка'), ('manual', 'Вручную')], default='manual', max_length=10, verbose_name='Источник')),
                ('status', models.CharField(choices=[('received', 'Получена'), ('validating', 'На проверке'), ('checked_ok', 'Проверена'), ('has_remarks', 'Замечания'), ('registered', 'В реестре'), ('issued', 'Выдана в ПР')], default='received', max_length=12, verbose_name='Статус')),
                ('storage_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь выдачи (сеть)')),
                ('archive_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Путь в архиве')),
                ('submitted_folder', models.CharField(blank=True, default='', max_length=300, verbose_name='Папка Подано')),
                ('accdb_task_code', models.CharField(blank=True, default='', help_text='[02 Задачи].Код задачи до маппинга на TaskNode (DOC-5)', max_length=20, verbose_name='Код задачи accdb')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_revisions', to='Emails.attachment', verbose_name='Вложение')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_revisions', to='Emails.email', verbose_name='Письмо')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='DocRegistry.docregisterentry', verbose_name='Запись реестра')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_revisions', to='ProjectTDL.tasknode', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Ревизия документации',
                'verbose_name_plural': 'Ревизии документации',
                'ordering': ['entry__code', 'rev_no'],
            },
        ),
        migrations.CreateModel(
            name='DocRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст замечания')),
                ('sheet_pdf', models.FileField(blank=True, null=True, upload_to='DocRegistry/remarks/%Y/%m/', verbose_name='Лист согласования (PDF)')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('reply_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответ получен')),
                ('reply_file', models.FileField(blank=True, null=True, upload_to='DocRegistry/remarks/%Y/%m/', verbose_name='Ответ подрядчика')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='DocRegistry.docrevision', verbose_name='Ревизия')),
            ],
            options={
                'verbose_name': 'Замечание',
                'verbose_name_plural': 'Замечания',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DocCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('PASS', 'Годно'), ('FAIL', 'Замечания')], max_length=4, verbose_name='Вердикт')),
                ('diff_json', models.JSONField(blank=True, default=dict, help_text='листы/штампы/размеры из revision_diff', verbose_name='Что изменилось')),
                ('checks_json', models.JSONField(blank=True, default=dict, verbose_name='Проверки П1–П4')),
                ('questions_md', models.TextField(blank=True, default='', verbose_name='Вопросы подрядчику')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='Проверено')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='DocRegistry.docrevision', verbose_name='Ревизия')),
            ],
            options={
                'verbose_name': 'Проверка ревизии',
                'verbose_name_plural': 'Проверки ревизий',
            },
        ),
        migrations.CreateModel(
            name='DocChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='Было')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='Стало')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('source', models.CharField(choices=[('manual', 'Руками'), ('api', 'API агента'), ('import', 'Импорт accdb')], default='manual', max_length=10, verbose_name='Источник')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelog', to='DocRegistry.docregisterentry', verbose_name='Запись реестра')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelog', to='DocRegistry.docrevision', verbose_name='Ревизия')),
            ],
            options={
                'verbose_name': 'Запись журнала РД',
                'verbose_name_plural': 'Журнал изменений РД',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='docrevision',
            constraint=models.UniqueConstraint(fields=('entry', 'rev_no'), name='docregistry_rev_unique'),
        ),
    ]
