# Generated by Django 5.2.16 on 2026-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocRegistry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docregisterentry',
            name='acts',
            field=models.CharField(blank=True, default='', help_text='accdb: Акты (max 289 в live)', max_length=500, verbose_name='Акты'),
        ),
        migrations.AlterField(
            model_name='docregisterentry',
            name='file_name',
            field=models.CharField(blank=True, default='', help_text='accdb: Назв Эл файла (max 771 в live)', max_length=1000, verbose_name='Имя эл. файла'),
        ),
    ]
