# Generated by Django 5.2.16 on 2026-09-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocRegistry', '0002_alter_docregisterentry_acts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrevision',
            name='entry',
            field=models.ForeignKey(blank=True, help_text='Пусто до шага 3 (register) — приём идёт раньше привязки к реестру', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='DocRegistry.docregisterentry', verbose_name='Запись реестра'),
        ),
    ]
