# Generated by Django 5.2.16 on 2026-09-10 13:04

import django.db.models.deletion
from django.db import migrations, models


def _null_old_codes(apps, schema_editor):
    # Старые CharField-колонки хранят коды-строки ('21'); in-place AlterField в FK
    # на SQLite не переживает FK-целостность. Записей-ревизий/связей ещё нет
    # (changelog без entry), поэтому записи удаляются — реимпорт восстановит
    # все 368 по тем же кодам accdb (код = стабильный id).
    schema_editor.execute('DELETE FROM DocRegistry_docregisterentry')


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('DocRegistry', '0003_alter_docrevision_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocBuilding',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код здания')),
                ('number', models.CharField(blank=True, default='', max_length=20, verbose_name='№ здания')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Наименование здания')),
            ],
            options={
                'verbose_name': 'Здание (справочник РД)',
                'verbose_name_plural': 'Здания (справочник РД)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocDeveloper',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Разработчик')),
            ],
            options={
                'verbose_name': 'Разработчик (справочник РД)',
                'verbose_name_plural': 'Разработчики (справочник РД)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocSection',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код раздела')),
                ('short', models.CharField(blank=True, default='', max_length=20, verbose_name='Раздел (шифр)')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Наименование раздела')),
            ],
            options={
                'verbose_name': 'Раздел (справочник РД)',
                'verbose_name_plural': 'Разделы (справочник РД)',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='docregisterentry',
            name='building_name',
        ),
        migrations.RemoveField(
            model_name='docregisterentry',
            name='contractor_new',
        ),
        migrations.RunPython(_null_old_codes, _noop),
        migrations.AddField(
            model_name='docremark',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='docremark',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_remarks', to='DocRegistry.docregisterentry', verbose_name='Запись реестра (история)'),
        ),
        migrations.AddField(
            model_name='docremark',
            name='remark_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата замечания'),
        ),
        migrations.AlterField(
            model_name='docremark',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='DocRegistry.docrevision', verbose_name='Ревизия'),
        ),
        migrations.AddField(
            model_name='docregisterentry',
            name='building',
            field=models.ForeignKey(blank=True, help_text='accdb: Наименование здания (код)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='DocRegistry.docbuilding', verbose_name='Наименование здания'),
        ),
        migrations.AlterField(
            model_name='docregisterentry',
            name='building_no',
            field=models.ForeignKey(blank=True, help_text='accdb: Номер здания (код)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_by_number', to='DocRegistry.docbuilding', verbose_name='Номер здания'),
        ),
        migrations.AddField(
            model_name='docregisterentry',
            name='developer',
            field=models.ForeignKey(blank=True, help_text='accdb: разраб_нов (код)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='DocRegistry.docdeveloper', verbose_name='Разраб.'),
        ),
        migrations.AlterField(
            model_name='docregisterentry',
            name='section',
            field=models.ForeignKey(blank=True, help_text='accdb: раздел (код)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='DocRegistry.docsection', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='DocSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='', max_length=200, verbose_name='Должность')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='Компания')),
                ('person', models.CharField(blank=True, default='', max_length=200, verbose_name='ФИО')),
                ('mark', models.CharField(blank=True, default='', max_length=100, verbose_name='Отметка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='DocRegistry.docbuilding', verbose_name='Здание (пусто — общий)')),
            ],
            options={
                'verbose_name': 'Подписант',
                'verbose_name_plural': 'Подписанты',
                'ordering': ['building__code', 'order'],
            },
        ),
    ]
