# Generated by Django 5.2.16 on 2026-09-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocRegistry', '0004_docbuilding_docdeveloper_docsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docissue',
            name='approval_pdf',
            field=models.FileField(blank=True, null=True, upload_to='DocRegistry/issues/%Y/%m/', verbose_name='Лист согласования (PDF)'),
        ),
    ]
