# Generated by Django 5.2.16 on 2026-09-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocRegistry', '0005_docissue_approval_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocProject',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код проекта')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Название')),
                ('customer', models.CharField(blank=True, default='', max_length=300, verbose_name='Заказчик')),
                ('object_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Объект')),
                ('object_address', models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес объекта')),
                ('designer', models.CharField(blank=True, default='', max_length=200, verbose_name='Проектировщик')),
            ],
            options={
                'verbose_name': 'Проект (шапка согласования)',
                'verbose_name_plural': 'Проекты (шапка согласования)',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='docregisterentry',
            name='project',
            field=models.ForeignKey(blank=True, help_text='М1/К1 — шапка листа (заказчик/объект)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='DocRegistry.docproject', verbose_name='Проект'),
        ),
    ]
