# Generated by Django 5.2.16 on 2026-09-11 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocRegistry', '0008_project_scoping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsigner',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='DocRegistry.docbuilding', verbose_name='Здание (пусто — общий)'),
        ),
    ]
