# Generated by Django 5.2.16 on 2026-09-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocRegistry', '0010_split_registries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docsigner',
            options={'ordering': ['order'], 'verbose_name': 'Подписант', 'verbose_name_plural': 'Подписанты'},
        ),
        migrations.AddField(
            model_name='k1issue',
            name='archived_old_rev',
            field=models.BooleanField(default=False, verbose_name='Старая ревизия убрана в архив'),
        ),
    ]
