# Generated by Django 5.2.16 on 2026-09-11 12:56

import DocRegistry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocRegistry', '0011_alter_docsigner_options_k1issue_archived_old_rev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k1issue',
            name='approval_pdf',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('issues'), verbose_name='Лист согласования (PDF)'),
        ),
        migrations.AlterField(
            model_name='k1issue',
            name='waybill_pdf',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('issues'), verbose_name='Накладная (PDF)'),
        ),
        migrations.AlterField(
            model_name='k1remark',
            name='reply_file',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('remarks'), verbose_name='Ответ подрядчика'),
        ),
        migrations.AlterField(
            model_name='k1remark',
            name='sheet_pdf',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('remarks'), verbose_name='Лист согласования (PDF)'),
        ),
        migrations.AlterField(
            model_name='k1revision',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('incoming'), verbose_name='Файл ревизии'),
        ),
        migrations.AlterField(
            model_name='m1issue',
            name='approval_pdf',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('issues'), verbose_name='Лист согласования (PDF)'),
        ),
        migrations.AlterField(
            model_name='m1issue',
            name='waybill_pdf',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('issues'), verbose_name='Накладная (PDF)'),
        ),
        migrations.AlterField(
            model_name='m1remark',
            name='reply_file',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('remarks'), verbose_name='Ответ подрядчика'),
        ),
        migrations.AlterField(
            model_name='m1remark',
            name='sheet_pdf',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('remarks'), verbose_name='Лист согласования (PDF)'),
        ),
        migrations.AlterField(
            model_name='m1revision',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=DocRegistry.models.RegistryUploadTo('incoming'), verbose_name='Файл ревизии'),
        ),
    ]
