# Generated by Django 5.0.4 on 2024-08-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование Здания')),
            ],
            options={
                'verbose_name': 'Здание Тип',
                'verbose_name_plural': 'Здания Тип',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DesignChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наим. Раздела')),
                ('short_name', models.CharField(max_length=150, verbose_name='Шифр раздела')),
            ],
            options={
                'verbose_name': 'Раздел Документации',
                'verbose_name_plural': 'Разделы Документации',
            },
        ),
        migrations.CreateModel(
            name='ProjectSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование Проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статус задач',
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подпроект')),
            ],
            options={
                'verbose_name': 'Подпроект',
                'verbose_name_plural': 'Подпроекты',
            },
        ),
        migrations.CreateModel(
            name='BuildingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер Здания')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StaticData.buildingtype', verbose_name='Тип здания')),
            ],
            options={
                'verbose_name': 'Здание Номер',
                'verbose_name_plural': 'Здания Номер',
            },
        ),
    ]
