# Generated by Django 5.2.16 on 2026-07-31 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0001_initial'),
        ('StaticData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsite',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='StaticData.category', verbose_name='Категория по умолчанию'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='default_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ProjectContract.contractor', verbose_name='Ответственный по умолчанию'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='default_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='StaticData.status', verbose_name='Статус по умолчанию'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='default_sub_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='StaticData.subproject', verbose_name='Проект по умолчанию'),
        ),
    ]
