# Generated by Django 4.2.18 on 2026-07-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectContract', '0002_remove_contract_sub_project'),
        ('ProjectTDL', '0011_alter_projectpin_options_remove_tasknode_sub_project_and_more'),
        ('StaticData', '0002_projectsite_default_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsite',
            name='default_sub_project',
        ),
        migrations.DeleteModel(
            name='SubProject',
        ),
    ]
