# Generated by Django 5.0.4 on 2024-06-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
            },
        ),
        migrations.CreateModel(
            name='PersonalProjectSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование Проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='PersonalContractPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Наименование платежа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('made_payment', models.BooleanField(default=False, verbose_name='Оплачено?')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='план.завершение')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalData.personalcontractor', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'договор Оплата',
                'verbose_name_plural': 'договоры Оплаты',
            },
        ),
        migrations.CreateModel(
            name='PersonalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('proposal_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proposal')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='план.завершение')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalData.personalcontractor', verbose_name='Подрядчик')),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalData.personalprojectsite', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
