# Generated by Django 6.0.7 on 2026-07-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Содержимое')),
                ('tags', models.CharField(blank=True, max_length=300, null=True, verbose_name='Теги (через запятую)')),
                ('pinned', models.BooleanField(default=False, verbose_name='Закреплено')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-pinned', '-update_stamp'],
            },
        ),
        migrations.CreateModel(
            name='PersonalPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('update_stamp', models.DateTimeField(auto_now=True, null=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Сервис')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='URL')),
                ('login', models.CharField(blank=True, max_length=200, null=True, verbose_name='Логин / e-mail')),
                ('password_enc', models.TextField(verbose_name='Пароль (шифр)')),
                ('category', models.CharField(choices=[('bank', 'Банк'), ('mail', 'Почта'), ('work', 'Работа'), ('shop', 'Покупки'), ('social', 'Соцсети'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранное')),
            ],
            options={
                'verbose_name': 'Пароль',
                'verbose_name_plural': 'Пароли',
                'ordering': ['-favorite', 'name'],
            },
        ),
    ]
