# Generated by Django 5.0.6 on 2024-06-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalcontractor',
            options={'verbose_name': 'Ресурс', 'verbose_name_plural': 'Ресурс'},
        ),
        migrations.AlterField(
            model_name='personalcontractpayments',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalData.personalcontract', verbose_name='Договор'),
        ),
    ]
